apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-deployment
  labels:
    app: 2048-game
  namespace: 2048-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 2048-game
  template:
    metadata:
      labels:
        app: 2048-game
    spec:
      containers:
      - name: 2048-game
        image: mradulsingh25/2048-game
        ports:
        - containerPort: 80 
