apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: two-zero-four-eight-ingress
  namespace: 2048-game
spec:
  rules:
  - host: "mradulsingh2048.com"
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: two-zero-four-eight-service
              port:
                number: 80
