apiVersion: v1
kind: Service
metadata:
  name: two-zero-four-eight-service
  namespace: 2048-game

spec:
  type: NodePort
  selector:
    app: 2048-game

  ports:
    - port: 80
      targetPort: 80
      nodePort: 30015
      protocol: TCP
