apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: gamespace

spec:
  type: NodePort
  selector:
    app: game-app

  ports:
    - port: 80
      targetPort: 80
      nodePort: 30015
      protocol: TCP
